[package]
name = "widow-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
widow-core = { path = "../widow-core" }
widow-scheduler = { path = "../widow-scheduler" }
widow-extractor = { path = "../widow-extractor" }
widow-embedder = { path = "../widow-embedder" }

tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
